[workspace.dependencies]
nostr = "0.22.0"
tokio = { version="1", features=["full"] }
log = "0.4.0"
env_logger = "0.10.0"

[workspace]
members = ["examples/state_machine", "examples/original", "examples/ex_test", "lib"]